"""fix posts

Revision ID: 06ff1ea94fc1
Revises: db87feed141c
Create Date: 2023-05-23 13:32:38.656204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ff1ea94fc1'
down_revision = 'db87feed141c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(length=2000), nullable=True))
        batch_op.alter_column('heading',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('timeCreated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeCreated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('time_created')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('heading',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.drop_column('body')

    # ### end Alembic commands ###
