"""Epic new stuff

Revision ID: 1c0ee785b379
Revises: db87feed141c
Create Date: 2023-05-22 09:36:51.263292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0ee785b379'
down_revision = 'db87feed141c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('timeCreated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeCreated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
